baseURL = "https://adi8712.github.io/"
languageCode = "en-us"
title = "Tech Talks"
theme = "rahul" # huge thanks to Rahul R. Nadkarni ;)

[taxonomies]
    tag = "tags"

[params]
    author = "Aditya Kumar Gupta"
    github = "https://github.com/Adi8712"
    linkedin = "https://linkedin.com/in/aditya-kgupta"
    twitter = "https://x.com/aditya_kgupta"
    mainSections = ["posts"]

[outputs]
home = ["HTML", "JSON", "RSS"]
section = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term = ["HTML", "RSS"]